/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.CallableStatement;
import java.util.ArrayList;
import main.Main;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class frmTaoLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmTaoLogin
     */
    public frmTaoLogin() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.loadGv();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loginame = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dsUser = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        mk = new javax.swing.JPasswordField();
        xnmk = new javax.swing.JPasswordField();
        pgv = new javax.swing.JRadioButton();
        khoa = new javax.swing.JRadioButton();
        kt = new javax.swing.JRadioButton();
        sv = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên đăng nhập");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tạo Login");

        jLabel3.setText("Mật khẩu");

        jLabel4.setText("Xác nhận mật khẩu");

        jLabel5.setText("User");

        dsUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsUserActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(pgv);
        pgv.setSelected(true);
        pgv.setText("PGV");
        pgv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pgvMouseClicked(evt);
            }
        });

        buttonGroup1.add(khoa);
        khoa.setText("KHOA");
        khoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khoaMouseClicked(evt);
            }
        });

        buttonGroup1.add(kt);
        kt.setText("KT");
        kt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ktMouseClicked(evt);
            }
        });
        kt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ktKeyPressed(evt);
            }
        });

        buttonGroup1.add(sv);
        sv.setText("SV");
        sv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                svMouseClicked(evt);
            }
        });

        jButton2.setText("Trang chủ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pgv, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xnmk)
                                    .addComponent(mk)
                                    .addComponent(loginame)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2))
                                            .addComponent(dsUser, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 21, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(khoa)
                                .addGap(18, 18, 18)
                                .addComponent(kt)
                                .addGap(18, 18, 18)
                                .addComponent(sv)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(loginame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(xnmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pgv)
                    .addComponent(khoa)
                    .addComponent(kt)
                    .addComponent(sv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dsUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // de trong
        String role ="";
        String loginn = loginame.getText();
        String password = String.valueOf(mk.getPassword());
        String xn = String.valueOf(xnmk.getPassword());
        String user = dsUser.getSelectedItem().toString();
        if (loginn.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống login");
        } else if (password.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống mật khẩu");
        } else if (xn.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống xác nhận");
        } else if (!xn.equals(password)) {
            JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu không đúng");
        } else if (this.checkTrungLogin(loginn) == 1) {
            JOptionPane.showMessageDialog(this, "Tên login này đã được sử dụng");
        } 
        else {
            try {
                PreparedStatement pr = Main.kn.prepareCall("{CALL SP_ADDLOGIN(?,?,?)}"); // tao login
                pr.setString(1, loginn);
                pr.setString(2, password);
                pr.setString(3, "QLDSV_TC");
                pr.execute();
                pr = Main.kn.prepareCall("{CALL SP_GRANTDBACCESS( ?, ?)}"); // mapping user
                pr.setString(1, loginn);
                pr.setString(2, user);
                pr.execute();
                
                if(sv.isSelected()) {
                    role = "SV";
                }
                else if(khoa.isSelected()) {
                    role = "KHOA";
                }
                else if(kt.isSelected()) {
                    role = "KT";
                }
                else {
                    role ="PGV";
                   
                    pr = Main.kn.prepareCall("{CALL sp_addsrvrolemember(?,?)}");
                    pr.setString(1, loginn);
                    pr.setString(2, "securityadmin");
                    pr.execute();
                }
                // them login vao role 
                pr = Main.kn.prepareCall("{CALL sp_addrolemember(?,?)}");
                pr.setString(1, role);
                pr.setString(2, user);
                pr.execute();
                
                
                JOptionPane.showMessageDialog(this, "Thêm login thành công");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        sv.setSelected(true);
        this.loadSv();
        
        

        // check login ton tai

    }//GEN-LAST:event_jButton1ActionPerformed
    public ArrayList<String> getDsGVAvailable() {
        ArrayList<String> ds = new ArrayList<>();
        try {
            PreparedStatement pr = Main.kn.prepareCall(
                    "select MAGV from GIANGVIEN "
                    + "except "
                    + "select name from sys.sysusers where issqluser = 1 ");
            ResultSet rs = pr.executeQuery();
            while (rs.next()) {
                ds.add(rs.getString(1));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return ds;
    }
    public ArrayList<String> getDssvAvailable() {
        ArrayList<String> ds = new ArrayList<>();
        try {
            PreparedStatement pr = Main.kn.prepareCall(
                    "select MASV from SINHVIEN "
                    + "except "
                    + "select name from sys.sysusers where issqluser = 1");
            ResultSet rs = pr.executeQuery();
            while (rs.next()) {
                ds.add(rs.getString(1));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return ds;
    }
    private void dsUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsUserActionPerformed

    private void svMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svMouseClicked
        // TODO add your handling code here:
        this.loadSv();
    }//GEN-LAST:event_svMouseClicked

    private void pgvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pgvMouseClicked
        // TODO add your handling code here:
        this.loadGv();
    }//GEN-LAST:event_pgvMouseClicked

    private void khoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khoaMouseClicked
        // TODO add your handling code here:
          this.loadGv();
    }//GEN-LAST:event_khoaMouseClicked

    private void ktKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ktKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ktKeyPressed

    private void ktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ktMouseClicked
        // TODO add your handling code here:
          this.loadGv();
    }//GEN-LAST:event_ktMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        MainForm f = new MainForm();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         // Determine the new location of the window
        int w = f.getSize().width;
        int h = f.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        // Move the window
        f.setLocation(x, y);
        f.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    public void loadGv() {
        dsUser.removeAllItems();
        ArrayList<String> ds = new ArrayList<>();
        ds = this.getDsGVAvailable();
        for (String s : ds) {
            dsUser.addItem(s);
        }
    }
    public void loadSv() {
        dsUser.removeAllItems();
        ArrayList<String> ds = new ArrayList<>();
        ds = this.getDssvAvailable();
        for (String s : ds) {
            dsUser.addItem(s);
        }
    }

    public int checkTrungLogin(String login) {
        int check = 0;
        try {
            CallableStatement pr = Main.kn.prepareCall("{? = CALL SP_TRUNG_LOGIN(?) }");
            pr.registerOutParameter(1, java.sql.Types.INTEGER);
            pr.setString(2, login);
            pr.execute();
            check = pr.getInt(1);
            if (check == 1) {

                return 1;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return 0;
    }

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTaoLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTaoLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTaoLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTaoLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTaoLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dsUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton khoa;
    private javax.swing.JRadioButton kt;
    private javax.swing.JTextField loginame;
    private javax.swing.JPasswordField mk;
    private javax.swing.JRadioButton pgv;
    private javax.swing.JRadioButton sv;
    private javax.swing.JPasswordField xnmk;
    // End of variables declaration//GEN-END:variables
}
