/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.Main;

/**
 *
 * @author LENOVO
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
         phanQuyen();     
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         // Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        // Move the window
        this.setLocation(x, y);

    }
    public void phanQuyen() {
        if(Main.role.equals("SV")) {
            role.setEnabled(false);
            
            
//            Component[] com = role.getComponents();
//            //Inside you action event where you want to disable everything
//            //Do the following
//            for (int a = 0; a < com.length; a++) {
//                 com[a].setEnabled(false);
//            }
            jButton1.setEnabled(false);
            taologin.setEnabled(false);
            no.setEnabled(false);
            jTabbedPane1.setEnabled(false);
            btnSinhVien.setVisible(false);
            btnLopSinhVien.setVisible(false);
            jButton3.setEnabled(false);
        }
        else if(Main.role.equals("PKT")) {
            jButton3.setEnabled(false);
            System.out.println("in");
            role.setVisible(false);
            btnDangKiLTC.setVisible(false);
            xoaloginkhoirole.setVisible(false);
        }
        else if(Main.role.equals("KHOA")){
            jButton3.setEnabled(false);
            no.setEnabled(false);
            btnDangKiLTC.setVisible(false);
        }
        else{
            btnDangKiLTC.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        not = new javax.swing.JTabbedPane();
        role = new javax.swing.JTabbedPane();
        r = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        no = new javax.swing.JTabbedPane();
        doimatkhau = new javax.swing.JTabbedPane();
        taologin = new javax.swing.JTabbedPane();
        xoaloginkhoirole = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnSinhVien = new javax.swing.JButton();
        btnDangKiLTC = new javax.swing.JButton();
        btnLopSinhVien = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        not.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notMouseClicked(evt);
            }
        });

        role.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roleMouseClicked(evt);
            }
        });

        r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rMouseClicked(evt);
            }
        });
        role.addTab("Cấp quyền cho Role", r);

        not.addTab("ROLE", role);

        jTabbedPane5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane5MouseClicked(evt);
            }
        });
        not.addTab("ĐĂNG XUẤT", jTabbedPane5);

        no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noMouseClicked(evt);
            }
        });

        doimatkhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doimatkhauMouseClicked(evt);
            }
        });
        no.addTab("Đổi mật khẩu", doimatkhau);

        taologin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taologinMouseClicked(evt);
            }
        });
        no.addTab("Tạo login", taologin);

        xoaloginkhoirole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoaloginkhoiroleMouseClicked(evt);
            }
        });
        no.addTab("Xóa login khỏi role", xoaloginkhoirole);

        not.addTab("LOGIN", no);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });
        not.addTab("LỚP TIN CHỈ", jTabbedPane1);

        btnSinhVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/student.png"))); // NOI18N
        btnSinhVien.setText("SINH VIÊN");
        btnSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinhVienActionPerformed(evt);
            }
        });

        btnDangKiLTC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDangKiLTC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btnDangKiLTC.setText("ĐĂNG KÍ LỚP TÍN CHỈ");
        btnDangKiLTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiLTCActionPerformed(evt);
            }
        });

        btnLopSinhVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLopSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/class.png"))); // NOI18N
        btnLopSinhVien.setText("LỚP");
        btnLopSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLopSinhVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnLopSinhVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSinhVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDangKiLTC)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangKiLTC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLopSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 201, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("", jPanel1);

        not.addTab("SINH VIÊN", jTabbedPane2);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jTabbedPane3.addTab("", jButton1);

        not.addTab("SAO LƯU", jTabbedPane3);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        not.addTab("TAO ROLE", jButton3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(not, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(not, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notMouseClicked
        // TODO add your handling code here:

     
    }//GEN-LAST:event_notMouseClicked

    private void jTabbedPane5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane5MouseClicked
        // TODO add your handling code here:
        Main.kn = null;
        Main.loginName = "";
        Main.password = "";
        Main.role = "";
        this.setVisible(false);
        new frmDangNhap().setVisible(true);
    }//GEN-LAST:event_jTabbedPane5MouseClicked

    private void roleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roleMouseClicked

    }//GEN-LAST:event_roleMouseClicked

    private void rMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rMouseClicked
        // TODO add your handling code here:
        if(!role.isEnabled()){
            return;
        }
        this.setVisible(false);
        new frmCapQuyenChoRole().setVisible(true);
    }//GEN-LAST:event_rMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        if(!jTabbedPane1.isEnabled()){
            return;
        }
        MoLopTinChi f = new MoLopTinChi();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         // Determine the new location of the window
        int w = f.getSize().width;
        int h = f.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        // Move the window
        f.setLocation(x, y);
        f.setVisible(true);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseClicked

    }//GEN-LAST:event_noMouseClicked

    private void xoaloginkhoiroleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoaloginkhoiroleMouseClicked
        // TODO add your handling code here:
        if(!no.isEnabled()){
            return;
        }
        this.setVisible(false);
        System.out.println("in222");
        frmXoaLogin1 f = new frmXoaLogin1();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         // Determine the new location of the window
        int w = f.getSize().width;
        int h = f.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        // Move the window
        f.setLocation(x, y);
        f.setVisible(true);
    }//GEN-LAST:event_xoaloginkhoiroleMouseClicked

    private void taologinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taologinMouseClicked
        // TODO add your handling code here:
        if(!no.isEnabled()){
            return;
        }
        frmTaoLogin f = new frmTaoLogin();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         // Determine the new location of the window
        int w = f.getSize().width;
        int h = f.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        // Move the window
        f.setLocation(x, y);
        f.setVisible(true);

    }//GEN-LAST:event_taologinMouseClicked

    private void doimatkhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doimatkhauMouseClicked
        // TODO add your handling code here:
        
        frmDoiMatKhau f = new frmDoiMatKhau();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         // Determine the new location of the window
        int w = f.getSize().width;
        int h = f.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        // Move the window
        f.setLocation(x, y);
        f.setVisible(true);
    }//GEN-LAST:event_doimatkhauMouseClicked

    private void btnSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinhVienActionPerformed
        try {
            // TODO add your handling code here:
            this.setVisible(false);
            FormSinhVien f = new FormSinhVien();
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            int w = f.getSize().width;
            int h = f.getSize().height;
            int x = (dim.width-w)/2;
            int y = (dim.height-h)/2;
            f.setLocation(x, y);
            f.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSinhVienActionPerformed

    private void btnDangKiLTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiLTCActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FormDangKi f = new FormDangKi();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = f.getSize().width;
        int h = f.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        f.setLocation(x, y);
        f.setVisible(true);
    }//GEN-LAST:event_btnDangKiLTCActionPerformed

    private void btnLopSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLopSinhVienActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FormLop().setVisible(true);
    }//GEN-LAST:event_btnLopSinhVienActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new FormBackup().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        this.setVisible(false);
        new taoRoleJava().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKiLTC;
    private javax.swing.JButton btnLopSinhVien;
    private javax.swing.JButton btnSinhVien;
    private javax.swing.JTabbedPane doimatkhau;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane no;
    private javax.swing.JTabbedPane not;
    private javax.swing.JTabbedPane r;
    private javax.swing.JTabbedPane role;
    private javax.swing.JTabbedPane taologin;
    private javax.swing.JTabbedPane xoaloginkhoirole;
    // End of variables declaration//GEN-END:variables
}
